### PR TITLE
Removed need for sorting of data before adding

### PR DESCRIPTION
**Pull request by matkey**
Means datapoints can be added out of order

### CODE REVIEW

**Comment by jjoe64** [comment]
thx.
need to check performance impact

**Comment by jjoe64** [comment]
Hi @matkey 
thanks for your work.
I thought about it, and I don't want to sort the data on graphview's side. The user should have the responsibility to input the correct order. 

About your second commit. I like the idea. I have one suggestion to make the API more easier. Could you please remove the flag "mMaxXAxisViewportLimitEnabled" and instead use the "mMaxXAxisViewportSize". 
if mMaxXAxisViewportSize == 0 it is disabled, otherwise it is disabled.

And can you create a new pull request with only one commit, which contains the max viewport limit stuff?

Thanks for contributing
Jonas

**Comment by matkey** [comment]
Hi Jonas,

Sure. Will make that tweak.
I am however struggling a bit with Github (first time using it....normally use SVN) so I might have to email it to you instead......

M

Date: Tue, 23 Aug 2016 04:34:10 -0700

**Comment by jjoe64** [comment]
would be much better via github merge request. then we also have your credits 👍 
In the worst case, you can commit it to this pull request (branch)  and I pick only the changes that I want, manually.

**Comment by matkey** [comment]
OK. Will attempt a pull request :)
By the way, the reasoning for the Sort is that in our case we are plotting data from wireless sensors. These sensors can buffer data when out of range. Once in range it sends the newest data first and so fills in the graph from right to left. This is why we added the sorting. Any suggestions for doing it another way?

**Comment by jjoe64** [comment]
OK I understand.
I think there are 3 possible solutions.
1) you create your own subclass of LineGraphSeries and override the appendData method and do the sorting. Here I think you have to change the visibility of some members in BaseSeries from private to protected. I'm fine with that to push it.
2) you collect the data from your sensor, sort it, and update the graph with a little latency.
3) you don't use appendData, but resetData and sort the data before calling it.

I think for performance reasons the 2nd solution is the most robust.

**Pull request closed without merging**
